name: 🐞 Bug Report
description: File a bug report
labels: [ bug ]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.
          required: true
  - type: textarea
    attributes:
      label: Bug description
      description: Detailed description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        Minimal code snippet to reproduce the bug.
        
        **IMPORTANT!** It should:
        - include all code needed to reproduce the issue
        - include all required imports
        - be self-contained - without references to any code outside
        - be as small as possible, without unrelated code from your project
        
        It should be possible to copy-paste the code and run it as-is.
        
        See the StackOverflow guide on how to create a Minimal, Complete, and Reproducible example:
        https://stackoverflow.com/help/minimal-reproducible-example
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      value: |
        - Node version: <!-- "node -v" output -->
        - Testing lib and version: <!-- e.g. Mocha, Jest, ... -->
        - Typescript version:
        - AWS SDK v3 Client mock version:
        - AWS JS SDK libs and versions:
            - <!-- e.g. @aws-sdk/client-sqs v3.10.0 -->
    validations:
      required: true
